# Cấu hình kết nối tới Database MySQL trên XAMPP
spring.datasource.url=jdbc:mysql://localhost:3307/phan_mem_dang_ky_tin_chi?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cho phép Spring Boot tự động hiển thị câu lệnh SQL và ánh xạ DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true